### ISSUE TITLE
accessing mongodb with authentication 

### ISSUE THREAD

**Issue by darwinharianto** [mongodb/mongo-swift-driver#209]
I don't know if this Has been asked or not, but I can't found it so here I want to ask about it.

I can create and access the mongoDB which I have created on a cloud server.
If I start it without 

> --auth

 options, I can access it perfectly, but I want to start with authentication options.
How do I put the username and password to mongoswift?

**Comment by patrickfreed** [comment]
To authenticate using a username and password, you can specify the credentials in the connection string you pass in when initializing a `MongoClient`. See the [Connection String URI](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format) documentation for more information on the format.

e.g.
```swift
let client = try MongoClient("mongodb://myuser:mypassword@localhost:27017")
// use client
```
Please let us know if you have any further questions.

**Comment by darwinharianto** [comment]
I tried what what you have said.

but that gives me this

```
 [conn10] received client metadata from <myIP>:52145 conn10: { driver: { name: "mongoc / MongoSwift", version: "1.13.0 / 0.0.2" }, os: { type: "Darwin", name: "iOS", version: "18.2.0", architecture: "iPhone7,2" }, platform: "cfg=0x00c22000 posix=200112 stdc=201112 CC=clang 9.0.0 (clang-900.0.39.2) CFLAGS="-fembed-bitcode -Wunguarded-availability" LDFLAGS=""" }
2019-02-14T01:47:02.900+0000 I NETWORK  [conn10] end connection <myIP> (0 connections now open)
```

no error but I don't get any data.

this is how I call the link

`let client = try MongoClient(connectionString: "mongodb://myId:mypass@myIP:27017")`

**Comment by patrickfreed** [comment]
The syntax appears correct. The client is just a handle for the server, though. In order to see any data, you need to query it.

e.g.
```swift
let client = try MongoClient(connectionString: "...")
let cursor = try client.listDatabases()
while let doc = cursor.next() {
     print(doc.extJSON)
}

if let err = cursor.error {
    print("error on cursor: \(err)")
}
```
Take a look at the documentation for [`MongoDatabase`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoDatabase.html) and [`MongoCollection`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCollection.html) for more ways to query the database.

**Comment by darwinharianto** [comment]
Maybe I explained it wrong,
<img width="1016" alt="screen shot 2019-02-15 at 9 59 47" src="https://user-images.githubusercontent.com/44696192/52827535-8f964480-3108-11e9-8e10-0d8a0883a578.png">

The one that I put at username and password, should be the same with 
`let client = try MongoClient(connectionString: "mongodb://username:password@myIP:27017")`
right?

I have put that.

And the way I do to get data is this

```
do{
            let client = try MongoClient(connectionString: "mongodb://username:password@myIP:27017")
            let db = try client.db("myDB")
            let collection = try db.collection("stock")
            let query: Document = []
            let documents = try collection.find(query)
            var mongoData = [ObjectResponse].init()
            documents.forEach { (document) in
                do{
                    let data = document.canonicalExtendedJSON.data(using: .utf8)
                    let decoder = JSONDecoder()
                    let decodeResponseMongo = try decoder.decode(ObjectResponseMongoDB.self, from: data!)
                    var decodeResponse = self.portingFromMongoDBToNormalObjectResponse(mongoDB: decodeResponseMongo)
                    let snippet = decodeResponse.owner
                    
                    if let range = snippet.range(of: "#") {
                        let character = snippet[range.upperBound...]
                        decodeResponse.owner = String(character).decodeUrl()!
                    }
                    decodeResponse.dataType = decodeResponse.dataType.decodeUrl()!
                    mongoData.append(decodeResponse)
                }catch{
                    print(error)
                }
            }
            callback(mongoData)
            
        }catch{
            print(error)
        }
```

**Comment by darwinharianto** [comment]
When I tried to write data, it gives an error

`commandError(message: "The SCRAM_SHA_256 authentication mechanism requires libmongoc built with ENABLE_SSL")`

Then I tried to resolve it. Seems like I need to install composer to do this.
But doing so, I need to uninstall Hyperledger Composer?
they both have the same starting command.

**Comment by patrickfreed** [comment]
Oh, okay. Your problem actually is with your installation of libmongoc (aka the mongo-c-driver). MongoSwift is a wrapper around libmongoc and uses it under the hood to implement a lot of stuff. 

In this case, your installation of libmongoc doesn't have SSL support, which means it doesn't have the tools necessary to operate the authentication mechanism (SCRAM-SHA-256). I'd suggest re-installing libmongoc either from source by following [these instructions](http://mongoc.org/libmongoc/current/installing.html) or from homebrew by running `brew install mongo-c-driver`. 

As a side note, as part of MongoSwift, we implemented `BSONDecoder` so that you can convert between your types and `Document` without needing `JSONEncoder`. Check out the documentation for that [here](https://mongodb.github.io/mongo-swift-driver/Classes/BSONDecoder.html#/s:10MongoSwift11BSONDecoderC20dateDecodingStrategyAC04DateeF0Ovp).

**Comment by darwinharianto** [comment]
Hello again.

Sorry to keep bugging you but I still have the same problem.
Here are some details.

I am running mongoDB at azure server using ubuntu 18.0.4

so what I need to do is `apt-get install libmongoc-1.0-0`
which give me this
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmongoc-1.0-0 is already the newest version (1.9.2+dfsg-1build1).`

reinstalling mongoDB with command instructed [here](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/). 

starting mongoDB with this ` mongod --auth --port 27017 --dbpath /data/db --bind_ip_all`

but I still have the same error message at my phone.
Is there something I'm missing?

**Comment by patrickfreed** [comment]
No worries, you're not bugging me at all. I'm happy to help.

So the libmongoc that needs to be installed with SSL support is the one running on your phone, not on the Ubuntu machine. Unfortunately, libmongoc does not support SSL on iOS yet. For more information as to why, see #141 and [CDRIVER-2850](https://jira.mongodb.org/browse/CDRIVER-2850).

Once that ticket is closed, you will be able to authenticate via username and password on mobile devices. In the meantime, you will only be able to connect to the database from iOS if authentication is disabled. Alternatively, you can write a web app that your device can talk to and query the database through that.

I apologize that this is somewhat of an unsatisfactory resolution to your question. I encourage you to vote for that ticket to make it a higher priority, and hopefully it will be fixed soon. I will discuss with the team to see if the libmongoc team can prioritize that issue.

**Comment by darwinharianto** [comment]
I see. Thanks for the clarification. So in the meantime I have to wait for the newer version.

How can I vote the ticket?

**Comment by patrickfreed** [comment]
We use [JIRA ](https://jira.mongodb.com) for tracking all the work we do at MongoDB. If you make an account there and navigate to [CDRIVER-2850](https://jira.mongodb.com/browse/CDRIVER-2850), you can click on the "Vote for this issue" button. Also, you can start watching the issue so that you get emails for any updates to its status.

**Comment by darwinharianto** [comment]
Allright, done.

Thank you for your time.

**Comment by alexboboc** [comment]
Sorry to revive this, but I am unclear on what really is the status of this. To my understanding, `mongo-swift-driver` can't be used on iOS applications if trying to access databases that require auth - am I correct? If that is the case, how is this even acceptable? It seems to make the whole driver majorly unusable.

**Comment by kmahar** [comment]
Hi @alexboboc.

The 0.1.3 release of the driver supports the two following use cases:
1) When used in an iOS application, communicating with an embedded version of MongoDB running on your iOS device.
2) When used in an application running on MacOS or Linux, communicating with any MongoDB server, including one on Atlas utilizing SSL.

At the time of the conversation above, we were also developing some higher-level libraries that would be utilizing this driver under the hood and allow syncing data between the embedded version of MongoDB and an instance running on Atlas. The design of these libraries, which are how we intended for people to use MongoDB on iOS, did not require MongoSwift or libmongoc to support using SSL on iOS. 
However, a few people (such as the user who initially opened this issue) expressed interest in using the driver directly in an iOS app to talk to a remote MongoDB server, hence the JIRA ticket linked above was opened.

All that said - a lot has changed since February. Specifically, MongoDB Mobile is being deprecated in favor of Realm. You can read more about the roadmap for MongoDB/Realm integration [here](https://www.mongodb.com/realm), but the short of it is that for iOS purposes we recommend you use Realm.

MongoSwift will remove support altogether for use on iOS in our upcoming 1.0 release. This library is now only meant for use case 2 that I mentioned above, and in particular supporting server-side Swift usage.

Hope that clears things up for you.
